### ISSUE TITLE
 bracketed paste only works the first time

### ISSUE THREAD

**Issue by sigoden** [nushell/reedline#648] opened 2023-10-17 12:08 UTC
**Platform** Ubuntu 22.04
**Terminal software** gnome-terminal

bracketed paste only works the first time. 

This bug does not exist on v0.19.1 but does on v0.25.0

## Steps to reproduce

1. run `cargo run --example demo`
2. paste multi-line content, successful, press `ctrl+c`, paste multi-line content again, it failed

## Screenshots/Screencaptures

![reedline](https://github.com/nushell/reedline/assets/4012553/afbe218c-1cc4-4531-86bb-46f82a23d6d8)

**Comment by fdncred** [comment] 2023-10-17 12:17
I can reproduce this on Ubuntu in WSL. I wonder if it's a bug in crossterm or if we've just implemented it wrong?

**Comment by sigoden** [comment] 2023-10-17 12:31
This bug may be related to

https://github.com/nushell/reedline/blob/adc20cb3710c6177203cb373604c10c6f089c41b/src/engine.rs#L633C1-L634C41

#598

**Comment by fdncred** [comment] 2023-10-17 12:43
Ya, that first link could be the issue. I'm not sure why we'd disable it on every read_line? Seems like we should check to see if it is meant to be enabled or not before automatically always disabling it?

Just playing around with the demo, I noticed that if I enable it on every loop, it works fine.
```rust
    loop {
        let res = line_editor.enable_bracketed_paste();
        let bracketed_paste_enabled = res.is_ok();
        if !bracketed_paste_enabled {
            println!("Warn: failed to enable bracketed paste mode: {res:?}");
        }

        let sig = line_editor.read_line(&prompt);
```
Lemme try to take that engine part out while I'm playing around and see if that fixes it.

**Comment by fdncred** [comment] 2023-10-17 12:45
ya, commenting out these lines makes it work too.
```rust
    pub fn read_line(&mut self, prompt: &dyn Prompt) -> Result<Signal> {
        terminal::enable_raw_mode()?;

        let result = self.read_line_helper(prompt);

        // #[cfg(not(target_os = "windows"))]
        // self.disable_bracketed_paste()?;

        if self.use_kitty_protocol {
            let _ = execute!(io::stdout(), event::PopKeyboardEnhancementFlags);
        }

        terminal::disable_raw_mode()?;
        result
    }
```

I wonder if we should have something like how the kitty protocol is checked? e.g. `if self.use_bracketed_paste { ... }`

**Comment by amtoine** [comment] 2023-10-17 16:19
@sigoden 
is this related to https://github.com/nushell/nushell/issues/9944 as well? :yum:

**Comment by LevitatingBusinessMan** [comment] 2023-11-03 02:19
Huh, so this is why I kept thinking that bracketed paste wasn't working yet when others said it did. The feature was literally disabled on Linux...

**Comment by fdncred** [comment] 2023-11-03 13:35
@LevitatingBusinessMan Feel free to create a PR that works better. It apparently works the first time you paste but not after that.

**Comment by LevitatingBusinessMan** [comment] 2023-11-04 00:30
The fix might just need to be to revert https://github.com/nushell/reedline/pull/598. Because a single application is being buggy doesn't mean you should disable an entire feature for a platform.

**Comment by fdncred** [comment] 2023-11-04 01:02
@LevitatingBusinessMan In case you're not aware, your comments here and in #598 are rude and disrespectful. Reedline and Nushell were written and are maintained by a handful of volunteers. We're all human and have different technical backgrounds, we make mistakes sometimes, and we have feelings. We're always up for constructive criticism but you're not being constructive. Please be mindful of this going forward. Thank you.

**Comment by LevitatingBusinessMan** [comment] 2023-11-04 23:13
@fdncred This project has thousands of daily downloads on crates.io. I'd argue a project of this size comes with certain responsibilities. I understand how bugs can be merged, it happens to every project. But in this case a feature was blatantly disabled on a platform and it was stated as a bugfix in the changelog.

This could've easily been prevented if the reviewer had actually reviewed the change (let alone tested it). Or if the merge had happened on the nushell side as was proposed originally.

**Comment by fdncred** [comment] 2023-11-04 23:32
What I was objecting to was your tone of dismissiveness and greater-than-thou attitude that was coming across. Again, maybe you didn't mean to act that way, but that's how it was coming across. I like to give people the benefit of the doubt because it's so hard to read emotion and intent in text sometimes. We all try hard, and everyone does their best. We have an excellent core-team. We don't appreciate people being rude and disrespectful to us and trying to bully us into making a change or undo a change.

Please feel free to submit a PR that you believe fixes the problem, otherwise let's please move on.

**Comment by LevitatingBusinessMan** [comment] 2023-11-06 22:21
Fixed in https://github.com/nushell/reedline/pull/657

**Closed** 2023-11-07 00:33 UTC
Labels: bug
